### ISSUE TITLE
单独使用BreathShodowView 动态去更改他的高度，阴影不明显了，咋回事？

### ISSUE THREAD

**Issue by liya7907** [pj567/ShimmerShadowLayout#1]
我想使用这个breathshaow组合一个语音起伏的动效组合控件，比如有20多个view放在一个linearlayout中，动态去更改view的高度，因为需要有呼吸和阴影的效果，这个控件看起来很合适，但是添加后发现不是很理想，想寻得你的帮助。。。

**Comment by pj567** [comment]
得根据这个计算方法来设置，和ShimmerShadowLayout有关系，ShimmerShadowLayout宽高要自适应，不然会裁剪子控件
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AndroidLee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月21日(星期四) 中午11:52
收件人:&nbsp;"pj567/ShimmerShadowLayout"<ShimmerShadowLayout@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[pj567/ShimmerShadowLayout] 单独使用BreathShodowView 动态去更改他的高度，阴影不明显了，咋回事？ (#1)





 
我想使用这个breathshaow组合一个语音起伏的动效组合控件，比如有20多个view放在一个linearlayout中，动态去更改view的高度，因为需要有呼吸和阴影的效果，这个控件看起来很合适，但是添加后发现不是很理想，想寻得你的帮助。。。
